// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHkNnbXD7TXoiDl5kZrhOKfDjmWQk4Lx8',
    appId: '1:612386875770:web:71276755b7ad58ac4c4ec3',
    messagingSenderId: '612386875770',
    projectId: 'agrovision-ai-21004',
    authDomain: 'agrovision-ai-21004.firebaseapp.com',
    storageBucket: 'agrovision-ai-21004.firebasestorage.app',
    measurementId: 'G-LDHFJPXBCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTtGXdBQmm0pZbbGjekTx0u21fwyKFitU',
    appId: '1:612386875770:android:97b4d0c195b3f3814c4ec3',
    messagingSenderId: '612386875770',
    projectId: 'agrovision-ai-21004',
    storageBucket: 'agrovision-ai-21004.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_YlX-9oea-dqWGkoWveEU3HH5YkNHTI',
    appId: '1:612386875770:ios:643ded14ba8993454c4ec3',
    messagingSenderId: '612386875770',
    projectId: 'agrovision-ai-21004',
    storageBucket: 'agrovision-ai-21004.firebasestorage.app',
    iosBundleId: 'com.example.agrinova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_YlX-9oea-dqWGkoWveEU3HH5YkNHTI',
    appId: '1:612386875770:ios:643ded14ba8993454c4ec3',
    messagingSenderId: '612386875770',
    projectId: 'agrovision-ai-21004',
    storageBucket: 'agrovision-ai-21004.firebasestorage.app',
    iosBundleId: 'com.example.agrinova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHkNnbXD7TXoiDl5kZrhOKfDjmWQk4Lx8',
    appId: '1:612386875770:web:7a5c710cc8f485b24c4ec3',
    messagingSenderId: '612386875770',
    projectId: 'agrovision-ai-21004',
    authDomain: 'agrovision-ai-21004.firebaseapp.com',
    storageBucket: 'agrovision-ai-21004.firebasestorage.app',
    measurementId: 'G-G2VJ92MQQC',
  );

}