// lib/main.dart
// Single-file app: AgroVision AI (Login with Phone OTP + Google Sign-in)
// Requires: lib/firebase_options.dart (generated by flutterfire)
// Pub dependencies: firebase_core, firebase_auth, google_sign_in, google_fonts, flutter_animate

import 'dart:async';
import 'dart:math';
import 'dart:io' show Platform;

import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:flutter_animate/flutter_animate.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'firebase_options.dart'; // generated by flutterfire

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const AgroVisionAIApp());
}

class AgroVisionAIApp extends StatelessWidget {
  const AgroVisionAIApp({super.key});

  static const Color primaryGreen = Color(0xFF2E7D32);
  static const Color darkGreen = Color(0xFF1B5E20);
  static const Color appBackground = Color(0xFFF6FBF6);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AgroVision AI',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        scaffoldBackgroundColor: appBackground,
        colorScheme: ColorScheme.fromSeed(seedColor: primaryGreen),
        textTheme: GoogleFonts.poppinsTextTheme(),
        useMaterial3: true,
      ),
      home: const SplashScreen(),
    );
  }
}

//
// ---------------- SPLASH SCREEN
//
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

class _SplashScreenState extends State<SplashScreen> with SingleTickerProviderStateMixin {
  late final AnimationController _controller;
  late final Animation<double> _fade;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(vsync: this, duration: const Duration(milliseconds: 900));
    _fade = CurvedAnimation(parent: _controller, curve: Curves.easeIn);
    _controller.forward();

    Future.delayed(const Duration(milliseconds: 1600), () async {
      // If user already signed in, go straight to home
      if (FirebaseAuth.instance.currentUser != null) {
        if (!mounted) return;
        Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const RootScreen()));
      } else {
        if (!mounted) return;
        Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const LoginScreen()));
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [Color(0xFF2E8B57), Color(0xFF1B5E20)],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
        child: Center(
          child: FadeTransition(
            opacity: _fade,
            child: Column(mainAxisSize: MainAxisSize.min, children: [
              Container(
                height: 110,
                width: 110,
                decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(26)),
                child: Icon(Icons.agriculture, size: 64, color: primary),
              ),
              const SizedBox(height: 14),
              Text('AgroVision AI',
                  style: GoogleFonts.poppins(fontSize: 28, fontWeight: FontWeight.w800, color: Colors.white)),
              const SizedBox(height: 6),
              Text('Smart Farming Assistant', style: GoogleFonts.poppins(color: Colors.white70)),
            ]),
          ),
        ),
      ),
    );
  }
}

//
// ---------------- LOGIN SCREEN (Phone OTP + Google)
//
class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});
  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> with TickerProviderStateMixin {
  final TextEditingController phoneController = TextEditingController();
  final TextEditingController otpController = TextEditingController();

  bool _codeSent = false;
  String? _verificationId;
  bool _loading = false;
  String _status = '';

  // leaves
  final List<_LeafParticle> leaves = [];
  final Random _rnd = Random();
  Timer? _leafTimer;

  late AnimationController _fadeCtrl;
  late Animation<double> _fadeIn;

  @override
  void initState() {
    super.initState();
    _fadeCtrl = AnimationController(vsync: this, duration: const Duration(milliseconds: 700));
    _fadeIn = CurvedAnimation(parent: _fadeCtrl, curve: Curves.easeIn);
    _fadeCtrl.forward();

    // create floating leaves
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final w = MediaQuery.of(context).size.width;
      final h = MediaQuery.of(context).size.height;
      for (int i = 0; i < 26; i++) {
        leaves.add(_LeafParticle(
          x: _rnd.nextDouble() * w,
          y: _rnd.nextDouble() * h,
          size: 8 + _rnd.nextDouble() * 14,
          speed: 0.3 + _rnd.nextDouble() * 0.8,
          direction: _rnd.nextDouble() * 2 * pi,
        ));
      }
      _leafTimer = Timer.periodic(const Duration(milliseconds: 30), (_) {
        setState(() {
          for (var leaf in leaves) {
            leaf.x += cos(leaf.direction) * leaf.speed;
            leaf.y += sin(leaf.direction) * leaf.speed;
            // wrap
            if (leaf.x < -40) leaf.x = MediaQuery.of(context).size.width + 20;
            if (leaf.x > MediaQuery.of(context).size.width + 40) leaf.x = -20;
            if (leaf.y < -40) leaf.y = MediaQuery.of(context).size.height + 20;
            if (leaf.y > MediaQuery.of(context).size.height + 40) leaf.y = -20;
          }
        });
      });
    });
  }

  @override
  void dispose() {
    phoneController.dispose();
    otpController.dispose();
    _leafTimer?.cancel();
    _fadeCtrl.dispose();
    super.dispose();
  }

  void _setStatus(String s) {
    setState(() => _status = s);
  }

  Future<void> _sendCode() async {
    final phone = phoneController.text.trim();
    if (phone.isEmpty) {
      _setStatus('Enter phone number (with country code, e.g. +91XXXXXXXXXX).');
      return;
    }
    setState(() {
      _loading = true;
      _status = 'Sending code...';
    });

    try {
      if (kIsWeb) {
        // Web: reCAPTCHA and verification handled by verifyPhoneNumber as well
        await FirebaseAuth.instance.verifyPhoneNumber(
          phoneNumber: phone,
          verificationCompleted: (credential) async {
            // Auto-resolving on web is rare
            await FirebaseAuth.instance.signInWithCredential(credential);
            if (!mounted) return;
            Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const RootScreen()));
          },
          verificationFailed: (e) {
            _setStatus('Verification failed: ${e.message}');
            setState(() => _loading = false);
          },
          codeSent: (verificationId, resendToken) {
            _verificationId = verificationId;
            setState(() {
              _codeSent = true;
              _loading = false;
              _status = 'Code sent. Enter OTP.';
            });
          },
          codeAutoRetrievalTimeout: (id) {
            _verificationId = id;
            _setStatus('Auto retrieval timeout. Enter OTP.');
            setState(() => _loading = false);
          },
          // timeout can be adjusted as needed
          timeout: const Duration(seconds: 60),
        );
      } else {
        // Mobile platforms
        await FirebaseAuth.instance.verifyPhoneNumber(
          phoneNumber: phone,
          verificationCompleted: (PhoneAuthCredential credential) async {
            // automatic verification (Android)
            await FirebaseAuth.instance.signInWithCredential(credential);
            if (!mounted) return;
            Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const RootScreen()));
          },
          verificationFailed: (FirebaseAuthException e) {
            _setStatus('Verification failed: ${e.message}');
            setState(() => _loading = false);
          },
          codeSent: (verificationId, int? resendToken) {
            _verificationId = verificationId;
            setState(() {
              _codeSent = true;
              _loading = false;
              _status = 'Code sent. Enter OTP.';
            });
          },
          codeAutoRetrievalTimeout: (String id) {
            _verificationId = id;
            _setStatus('Auto retrieval timeout. Enter OTP.');
            setState(() => _loading = false);
          },
          timeout: const Duration(seconds: 60),
        );
      }
    } catch (e) {
      _setStatus('Failed to send code: $e');
      setState(() => _loading = false);
    }
  }

  Future<void> _verifyOtpAndSignIn() async {
    final code = otpController.text.trim();
    if (code.isEmpty || _verificationId == null) {
      _setStatus('Enter the OTP sent to your phone.');
      return;
    }
    setState(() {
      _loading = true;
      _status = 'Verifying...';
    });

    try {
      final credential = PhoneAuthProvider.credential(verificationId: _verificationId!, smsCode: code);
      await FirebaseAuth.instance.signInWithCredential(credential);
      if (!mounted) return;
      Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const RootScreen()));
    } on FirebaseAuthException catch (e) {
      _setStatus('Failed to sign in: ${e.message}');
      setState(() => _loading = false);
    } catch (e) {
      _setStatus('Error: $e');
      setState(() => _loading = false);
    }
  }

  Future<void> _signInWithGoogle() async {
    setState(() {
      _loading = true;
      _status = 'Signing in with Google...';
    });
    try {
      if (kIsWeb) {
        // Web: use GoogleAuthProvider signInWithPopup
        final googleProvider = GoogleAuthProvider();
        googleProvider.addScope('email');
        await FirebaseAuth.instance.signInWithPopup(googleProvider);
      } else {
        // Mobile: use google_sign_in to get credentials
        final GoogleSignIn googleSignIn = GoogleSignIn();
        final GoogleSignInAccount? account = await googleSignIn.signIn();
        if (account == null) {
          setState(() {
            _loading = false;
            _status = 'Google sign-in cancelled';
          });
          return;
        }
        final GoogleSignInAuthentication auth = await account.authentication;
        final credential = GoogleAuthProvider.credential(
          accessToken: auth.accessToken,
          idToken: auth.idToken,
        );
        await FirebaseAuth.instance.signInWithCredential(credential);
      }
      if (!mounted) return;
      Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const RootScreen()));
    } on FirebaseAuthException catch (e) {
      _setStatus('Google sign-in failed: ${e.message}');
    } catch (e) {
      _setStatus('Google sign-in error: $e');
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  Widget _buildPhoneInput() {
    return Column(children: [
      Align(alignment: Alignment.centerLeft, child: Text('Phone number', style: GoogleFonts.poppins(fontWeight: FontWeight.w600))),
      const SizedBox(height: 8),
      TextField(
        controller: phoneController,
        keyboardType: TextInputType.phone,
        decoration: InputDecoration(
          hintText: '+91XXXXXXXXXX',
          filled: true,
          fillColor: Colors.green.shade50,
          prefixIcon: const Icon(Icons.phone),
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
        ),
      ),
      const SizedBox(height: 12),
      SizedBox(
        width: double.infinity,
        height: 48,
        child: ElevatedButton(
          style: ElevatedButton.styleFrom(backgroundColor: AgroVisionAIApp.primaryGreen, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
          onPressed: _sendCode,
          child: Text('Send OTP', style: GoogleFonts.poppins(fontWeight: FontWeight.w700, color: Colors.white)),
        ),
      ),
    ]);
  }

  Widget _buildOtpInput() {
    return Column(children: [
      Align(alignment: Alignment.centerLeft, child: Text('Enter OTP', style: GoogleFonts.poppins(fontWeight: FontWeight.w600))),
      const SizedBox(height: 8),
      TextField(
        controller: otpController,
        keyboardType: TextInputType.number,
        decoration: InputDecoration(
          hintText: '6-digit code',
          filled: true,
          fillColor: Colors.green.shade50,
          prefixIcon: const Icon(Icons.message),
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: BorderSide.none),
        ),
      ),
      const SizedBox(height: 12),
      SizedBox(
        width: double.infinity,
        height: 48,
        child: ElevatedButton(
          style: ElevatedButton.styleFrom(backgroundColor: AgroVisionAIApp.primaryGreen, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12))),
          onPressed: _verifyOtpAndSignIn,
          child: Text('Verify OTP', style: GoogleFonts.poppins(fontWeight: FontWeight.w700, color: Colors.white)),
        ),
      ),
      const SizedBox(height: 8),
      TextButton(onPressed: () => setState(() => _codeSent = false), child: Text('Change phone number', style: GoogleFonts.poppins(color: Colors.black54)))
    ]);
  }

  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(
      backgroundColor: Colors.white,
      body: Stack(children: [
        // floating leaves background
        ...leaves.map((leaf) {
          return Positioned(
            left: leaf.x,
            top: leaf.y,
            child: Opacity(opacity: 0.28, child: Transform.rotate(angle: leaf.direction, child: Icon(Icons.eco, size: leaf.size, color: primary.withOpacity(0.6)))),
          );
        }).toList(),

        SafeArea(
          child: FadeTransition(
            opacity: _fadeIn,
            child: Center(
              child: SingleChildScrollView(
                padding: const EdgeInsets.symmetric(horizontal: 22),
                child: Column(mainAxisSize: MainAxisSize.min, children: [
                  Container(
                    height: 100,
                    width: 100,
                    decoration: BoxDecoration(color: primary.withOpacity(0.12), borderRadius: BorderRadius.circular(20)),
                    child: Icon(Icons.agriculture, size: 56, color: primary),
                  ).animate().scale(duration: 500.ms, curve: Curves.easeOutBack),
                  const SizedBox(height: 14),
                  Text('AgroVision AI', style: GoogleFonts.poppins(fontSize: 26, fontWeight: FontWeight.w800, color: AgroVisionAIApp.primaryGreen)),
                  const SizedBox(height: 6),
                  Text('Smart Farming Assistant', style: GoogleFonts.poppins(color: Colors.black54)),
                  const SizedBox(height: 18),

                  // Either phone input or OTP input
                  _codeSent ? _buildOtpInput() : _buildPhoneInput(),

                  const SizedBox(height: 14),

                  // Divider & Google sign-in
                  Row(children: const [Expanded(child: Divider()), Padding(padding: EdgeInsets.symmetric(horizontal: 8), child: Text('OR')), Expanded(child: Divider())]),
                  const SizedBox(height: 12),

                  // Google button
                  GestureDetector(
                    onTap: _signInWithGoogle,
                    child: Container(
                      height: 50,
                      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12), border: Border.all(color: Colors.grey.shade300), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 6, offset: const Offset(0, 3))]),
                      child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [
                        Image.network('https://upload.wikimedia.org/wikipedia/commons/0/09/IOS_Google_icon.png', height: 22),
                        const SizedBox(width: 10),
                        Text('Continue with Google', style: GoogleFonts.poppins(fontWeight: FontWeight.w700)),
                      ]),
                    ),
                  ),

                  const SizedBox(height: 8),

                  if (_loading) Column(children: [const SizedBox(height: 8), const CircularProgressIndicator(), const SizedBox(height: 8)]),
                  if (_status.isNotEmpty) Text(_status, style: const TextStyle(color: Colors.black54)),
                  const SizedBox(height: 20),
                ]),
              ),
            ),
          ),
        ),
      ]),
    );
  }
}

class _LeafParticle {
  double x;
  double y;
  double size;
  double speed;
  double direction;
  _LeafParticle({required this.x, required this.y, required this.size, required this.speed, required this.direction});
}

//
// ---------------- ROOT SCREEN (Bottom nav + pages)
//
class RootScreen extends StatefulWidget {
  const RootScreen({super.key});
  @override
  State<RootScreen> createState() => _RootScreenState();
}

class _RootScreenState extends State<RootScreen> with TickerProviderStateMixin {
  int _index = 0;
  late final PageController _pageController;
  final List<Widget> _pages = const [CombinedHomePage(), InsightsPage(), DetectorPage(), ChatPage(), ProfilePage()];

  @override
  void initState() {
    super.initState();
    _pageController = PageController(initialPage: _index);
  }

  void _onNav(int i) {
    setState(() => _index = i);
    _pageController.jumpToPage(i);
  }

  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: Text('AgroVision AI', style: GoogleFonts.poppins(fontWeight: FontWeight.w700, color: Colors.white)),
        actions: [IconButton(onPressed: () {}, icon: const Icon(Icons.notifications_none, color: Colors.white))],
      ),
      body: Stack(children: [
        Container(
          height: 240,
          decoration: const BoxDecoration(
            gradient: LinearGradient(colors: [Color(0xFF2E8B57), Color(0xFF1B5E20)], begin: Alignment.topLeft, end: Alignment.bottomRight),
            borderRadius: BorderRadius.only(bottomLeft: Radius.circular(36), bottomRight: Radius.circular(36)),
          ),
        ),
        Positioned.fill(
          top: 120,
          child: ClipRRect(
            borderRadius: const BorderRadius.vertical(top: Radius.circular(28)),
            child: Container(
              color: Colors.grey[50],
              child: PageView(controller: _pageController, physics: const NeverScrollableScrollPhysics(), children: _pages),
            ),
          ),
        ),
        SafeArea(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 18.0, vertical: 12),
            child: Row(children: [
              Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                Text('Welcome back,', style: TextStyle(color: Colors.white.withOpacity(0.9), fontSize: 13)),
                const SizedBox(height: 4),
                Text('Chirag 👋', style: GoogleFonts.poppins(color: Colors.white, fontSize: 22, fontWeight: FontWeight.w800)),
              ]),
              const Spacer(),
              GestureDetector(
                onTap: () {},
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(color: Colors.white.withOpacity(0.12), borderRadius: BorderRadius.circular(12)),
                  child: CircleAvatar(radius: 18, backgroundColor: Colors.white, child: Icon(Icons.person, color: primary)),
                ),
              ),
            ]),
          ),
        ),
      ]),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Ask Nova (voice) — coming soon'))),
        backgroundColor: Colors.white,
        icon: Icon(Icons.mic, color: primary),
        label: Text('Ask Nova', style: TextStyle(color: primary, fontWeight: FontWeight.w700)),
      ),
      floatingActionButtonLocation: FloatingActionButtonLocation.centerDocked,
      bottomNavigationBar: BottomAppBar(
        shape: const CircularNotchedRectangle(),
        notchMargin: 8,
        color: Colors.white,
        child: SizedBox(
          height: 66,
          child: Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [
            _navItem(Icons.home, 'Home', 0),
            _navItem(Icons.insights, 'Insights', 1),
            const SizedBox(width: 48),
            _navItem(Icons.camera_alt, 'Detect', 2),
            _navItem(Icons.chat_bubble_outline, 'Chat', 3),
          ]),
        ),
      ),
    );
  }

  Widget _navItem(IconData icon, String label, int idx) {
    final active = idx == _index;
    return InkWell(
      onTap: () => _onNav(idx),
      child: Column(mainAxisSize: MainAxisSize.min, children: [
        const SizedBox(height: 8),
        Icon(icon, color: active ? AgroVisionAIApp.primaryGreen : Colors.grey[600]),
        const SizedBox(height: 4),
        Text(label, style: TextStyle(fontSize: 12, color: active ? AgroVisionAIApp.primaryGreen : Colors.grey[600])),
      ]),
    );
  }
}

//
// ---------------- HOME PAGE (Combined with 7 groups)
//
class CombinedHomePage extends StatelessWidget {
  const CombinedHomePage({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return SafeArea(
      child: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(18, 18, 18, 24),
        child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Row(children: [
            Expanded(child: StatGlassCard(title: 'Soil Health', value: 'Good', subtitle: 'N:28 P:12 K:30', icon: Icons.grass, accent: primary)),
            const SizedBox(width: 12),
            Expanded(child: StatGlassCard(title: 'Weather', value: 'Cloudy', subtitle: '21°C • Rain 40%', icon: Icons.cloud, accent: Colors.blueAccent)),
          ]),
          const SizedBox(height: 16),

          PromoWide(
            title: 'AI Soil Analysis',
            subtitle: 'Upload soil report or image → get fertilizer & micronutrient plan',
            accent1: primary,
            accent2: AgroVisionAIApp.darkGreen,
            icon: Icons.analytics,
          ).animate().slideY(begin: 0.2, duration: 600.ms).fadeIn(duration: 600.ms),

          const SizedBox(height: 18),

          Text('Pest Hotspots', style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: 8),
          const MapPreviewCard(),

          const SizedBox(height: 16),
          Text('Tool Categories', style: Theme.of(context).textTheme.titleMedium),
          const SizedBox(height: 10),

          FeatureGroupFancy(
            title: 'Crop Monitoring',
            subtitle: 'Pest & yield insights',
            icon: Icons.agriculture,
            items: [
              FeatureItem('Pest Prediction', Icons.bug_report_outlined, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const PestMapScreen()));
              }),
              FeatureItem('Yield Prediction', Icons.show_chart_rounded, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const YieldScreen()));
              }),
            ],
          ),

          FeatureGroupFancy(
            title: 'Disease Management',
            subtitle: 'Detect & recommend',
            icon: Icons.healing,
            items: [
              FeatureItem('Disease Detector', Icons.camera_alt, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const DetectorPage()));
              }),
              FeatureItem('Crop Recommendation', Icons.support, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const CropRecommendationScreen()));
              }),
            ],
          ),

          FeatureGroupFancy(
            title: 'Soil & Nutrient',
            subtitle: 'Micronutrients & soil health',
            icon: Icons.biotech,
            items: [
              FeatureItem('Micronutrient', Icons.biotech_rounded, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const MicronutrientScreen()));
              }),
              FeatureItem('Soil Health', Icons.thermostat, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const SoilHealthScreen()));
              }),
            ],
          ),

          FeatureGroupFancy(
            title: 'Soil Tools',
            subtitle: 'Planner & lab',
            icon: Icons.science,
            items: [
              FeatureItem('Fertiliser Planner', Icons.science_outlined, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const FertilizerPlannerScreen()));
              }),
              FeatureItem('Micronutrient Lab', Icons.upload_file, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const MicronutrientLabScreen()));
              }),
            ],
          ),

          FeatureGroupFancy(
            title: 'Market & Finance',
            subtitle: 'Credits & prices',
            icon: Icons.account_balance_wallet,
            items: [
              FeatureItem('Agro Credits', Icons.account_balance_wallet, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const AgroCreditsScreen()));
              }),
              FeatureItem('Market Prices', Icons.stacked_bar_chart, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const MarketPricesScreen()));
              }),
            ],
          ),

          FeatureGroupFancy(
            title: 'Community',
            subtitle: 'Learn & ask',
            icon: Icons.forum,
            items: [
              FeatureItem('Community Learning', Icons.forum_outlined, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const CommunityLearningScreen()));
              }),
              FeatureItem('Ask Expert', Icons.support_agent, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const AskExpertScreen()));
              }),
            ],
          ),

          FeatureGroupFancy(
            title: 'Tools & Alerts',
            subtitle: 'AR, explainability & reminders',
            icon: Icons.build_circle,
            items: [
              FeatureItem('AR View', Icons.view_in_ar_outlined, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const ARPlaceholderScreen()));
              }),
              FeatureItem('Explainability', Icons.psychology_alt_outlined, () {
                Navigator.of(context).push(MaterialPageRoute(builder: (_) => const ExplainabilityScreen()));
              }),
            ],
          ),

          const SizedBox(height: 6),
          Row(children: [
            Expanded(child: SmallCard(title: 'Alerts & Reminders', subtitle: '3 upcoming', icon: Icons.notifications_active, color: Colors.orange)),
            const SizedBox(width: 12),
            Expanded(child: SmallCard(title: 'Agro Credits', subtitle: '₹1,200', icon: Icons.account_balance_wallet, color: Colors.green)),
          ]),
          const SizedBox(height: 18),
        ]),
      ),
    );
  }
}

//
// ---------------- REUSABLE WIDGETS
//
class GlassCard extends StatelessWidget {
  final Widget child;
  const GlassCard({required this.child, super.key});
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(14), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 10, offset: const Offset(0, 6))]),
      child: child,
    );
  }
}

class StatGlassCard extends StatelessWidget {
  final String title, value, subtitle;
  final IconData icon;
  final Color accent;
  const StatGlassCard({required this.title, required this.value, required this.subtitle, required this.icon, required this.accent, super.key});

  @override
  Widget build(BuildContext context) {
    return GlassCard(
      child: Row(children: [
        Container(padding: const EdgeInsets.all(10), decoration: BoxDecoration(color: accent.withOpacity(0.12), shape: BoxShape.circle), child: Icon(icon, color: accent)),
        const SizedBox(width: 12),
        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Text(title, style: const TextStyle(color: Colors.black54)),
          const SizedBox(height: 6),
          Text(value, style: const TextStyle(fontWeight: FontWeight.w800)),
          const SizedBox(height: 4),
          Text(subtitle, style: const TextStyle(color: Colors.black45, fontSize: 12)),
        ])),
      ]),
    );
  }
}

class PromoWide extends StatelessWidget {
  final String title, subtitle;
  final Color accent1, accent2;
  final IconData icon;
  const PromoWide({required this.title, required this.subtitle, required this.accent1, required this.accent2, required this.icon, super.key});

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('AI Soil Analysis coming soon'))),
      child: Container(
        height: 110,
        decoration: BoxDecoration(
          gradient: LinearGradient(colors: [accent1, accent2]),
          borderRadius: BorderRadius.circular(14),
          boxShadow: [BoxShadow(color: accent1.withOpacity(0.22), blurRadius: 12, offset: const Offset(0, 6))],
        ),
        padding: const EdgeInsets.all(12),
        child: Row(children: [
          Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [
            Text(title, style: const TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w800)),
            const SizedBox(height: 6),
            Text(subtitle, style: const TextStyle(color: Colors.white70)),
          ])),
          CircleAvatar(radius: 26, backgroundColor: Colors.white24, child: Icon(icon, color: Colors.white, size: 28)),
        ]),
      ),
    );
  }
}

class MapPreviewCard extends StatelessWidget {
  const MapPreviewCard({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Container(
      height: 160,
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(14), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 12, offset: const Offset(0, 6))]),
      padding: const EdgeInsets.all(12),
      child: Column(children: [
        Expanded(
          child: Container(
            decoration: BoxDecoration(borderRadius: BorderRadius.circular(12), color: Colors.green.shade50),
            child: const Center(child: Text('Map preview • Pest heatmap placeholder', style: TextStyle(color: Colors.black54))),
          ),
        ),
        const SizedBox(height: 10),
        Row(children: [
          Icon(Icons.place, color: primary),
          const SizedBox(width: 8),
          const Expanded(child: Text('Hotspots last 7 days')),
          ElevatedButton(onPressed: () {}, style: ElevatedButton.styleFrom(backgroundColor: primary), child: const Text('View Map')),
        ]),
      ]),
    );
  }
}

class SmallCard extends StatelessWidget {
  final String title, subtitle;
  final IconData icon;
  final Color color;
  const SmallCard({required this.title, required this.subtitle, required this.icon, required this.color, super.key});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 10, offset: const Offset(0, 6))]),
      child: Row(children: [
        CircleAvatar(radius: 22, backgroundColor: color.withOpacity(0.12), child: Icon(icon, color: color)),
        const SizedBox(width: 12),
        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 4), Text(subtitle, style: const TextStyle(color: Colors.black54, fontSize: 12))])),
      ]),
    );
  }
}

//
// ---------------- FEATURE GROUP WIDGETS
//
class FeatureGroupFancy extends StatelessWidget {
  final String title;
  final String subtitle;
  final IconData icon;
  final List<FeatureItem> items;
  const FeatureGroupFancy({super.key, required this.title, required this.subtitle, required this.icon, required this.items});

  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    final rowItems = List<FeatureItem>.from(items);
    if (rowItems.length == 1) rowItems.add(FeatureItem('', Icons.circle_outlined, () {}));
    return Container(
      margin: const EdgeInsets.only(bottom: 14),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(color: const Color(0xFFF7F8F2), borderRadius: BorderRadius.circular(16), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 6)]),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          Container(padding: const EdgeInsets.all(8), decoration: BoxDecoration(color: Colors.green.shade50, borderRadius: BorderRadius.circular(8)), child: Icon(icon, color: primary)),
          const SizedBox(width: 10),
          Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            Text(title, style: TextStyle(fontSize: 16, fontWeight: FontWeight.w700, color: primary)),
            const SizedBox(height: 4),
            Text(subtitle, style: const TextStyle(color: Colors.black54, fontSize: 12)),
          ]),
        ]),
        const SizedBox(height: 12),
        Row(children: [
          _buildTile(context, rowItems[0]),
          const SizedBox(width: 10),
          _buildTile(context, rowItems[1]),
        ]),
      ]),
    );
  }

  Widget _buildTile(BuildContext context, FeatureItem item) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Expanded(
      child: GestureDetector(
        onTap: item.onTap,
        child: Container(
          height: 100,
          decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12), border: Border.all(color: Colors.green.withOpacity(0.06)), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 8, offset: const Offset(0, 6))]),
          child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
            Container(height: 48, width: 48, decoration: BoxDecoration(color: Colors.green.shade50, borderRadius: BorderRadius.circular(10)), child: Icon(item.icon, color: primary, size: 26)),
            const SizedBox(height: 8),
            Text(item.title, textAlign: TextAlign.center, style: const TextStyle(fontWeight: FontWeight.w600, color: Colors.black87, fontSize: 13)),
          ]),
        ),
      ),
    );
  }
}

class FeatureItem {
  final String title;
  final IconData icon;
  final VoidCallback onTap;
  FeatureItem(this.title, this.icon, this.onTap);
}

//
// ---------------- CHAT / BUBBLE
//
class ChatPage extends StatelessWidget {
  const ChatPage({super.key});
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Column(children: [
        Padding(padding: const EdgeInsets.all(16.0), child: Row(children: [
          CircleAvatar(radius: 24, backgroundColor: Colors.green.shade50, child: Icon(Icons.agriculture, color: AgroVisionAIApp.primaryGreen)),
          const SizedBox(width: 12),
          Column(crossAxisAlignment: CrossAxisAlignment.start, children: const [Text('Krishi Sakhi', style: TextStyle(fontWeight: FontWeight.w700)), Text('Your farming assistant', style: TextStyle(color: Colors.black54, fontSize: 12))]),
          const Spacer(),
          IconButton(onPressed: () {}, icon: const Icon(Icons.info_outline)),
        ])),
        const Divider(height: 1),
        Expanded(child: ListView(padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 16), children: const [
          ChatBubble(text: 'Hi! How can I help you today?', isMe: false),
          ChatBubble(text: 'My tomato leaves have spots — what to do?', isMe: true),
          ChatBubble(text: 'Looks like early blight. Remove affected leaves and apply recommended fungicide.', isMe: false),
        ])),
        Padding(padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 12), child: Row(children: [
          Expanded(child: Container(padding: const EdgeInsets.symmetric(horizontal: 12), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.03), blurRadius: 8)]), child: const TextField(decoration: InputDecoration(border: InputBorder.none, hintText: 'Ask Krishi Sakhi...')))),
          const SizedBox(width: 8),
          FloatingActionButton(onPressed: () {}, mini: true, child: const Icon(Icons.send)),
        ])),
      ]),
    );
  }
}

class ChatBubble extends StatelessWidget {
  final String text;
  final bool isMe;
  const ChatBubble({required this.text, required this.isMe, super.key});
  @override
  Widget build(BuildContext context) {
    return Align(
      alignment: isMe ? Alignment.centerRight : Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.symmetric(vertical: 6),
        padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
        constraints: BoxConstraints(maxWidth: MediaQuery.of(context).size.width * 0.75),
        decoration: BoxDecoration(color: isMe ? AgroVisionAIApp.primaryGreen : Colors.grey[200], borderRadius: BorderRadius.circular(12)),
        child: Text(text, style: TextStyle(color: isMe ? Colors.white : Colors.black87)),
      ),
    );
  }
}

//
// ---------------- FEATURE SCREENS (placeholders)
//
class PestMapScreen extends StatelessWidget {
  const PestMapScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(
      appBar: AppBar(title: const Text('Pest Prediction Map'), backgroundColor: primary),
      body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [
        Expanded(child: Container(decoration: BoxDecoration(color: Colors.green.shade50, borderRadius: BorderRadius.circular(14), boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.04), blurRadius: 10, offset: const Offset(0, 6))]), child: const Center(child: Text('Interactive map will be here (flutter_map / google_maps)', style: TextStyle(color: Colors.black54))))),
        const SizedBox(height: 12),
        GlassCard(child: Column(children: [Row(children: [Icon(Icons.place, color: primary), const SizedBox(width: 8), const Expanded(child: Text('Hotspots near your area (last 7 days)'))]), const SizedBox(height: 10), Wrap(spacing: 8, children: [Chip(label: const Text('Locust (12)'), backgroundColor: Colors.orange.shade50), Chip(label: const Text('Leaf Miner (8)'), backgroundColor: Colors.brown.shade50), Chip(label: const Text('Stem Borer (4)'), backgroundColor: Colors.red.shade50)])])),
      ])),
    );
  }
}

class YieldScreen extends StatefulWidget {
  const YieldScreen({super.key});
  @override
  State<YieldScreen> createState() => _YieldScreenState();
}

class _YieldScreenState extends State<YieldScreen> {
  final TextEditingController cropCtrl = TextEditingController();
  final TextEditingController areaCtrl = TextEditingController();
  String? _result;

  void _predict() {
    final crop = cropCtrl.text.trim();
    final area = double.tryParse(areaCtrl.text.trim()) ?? 0.0;
    double base = 2.0;
    if (crop.toLowerCase().contains('rice')) base = 4.0;
    if (crop.toLowerCase().contains('wheat')) base = 3.2;
    if (crop.toLowerCase().contains('maize') || crop.toLowerCase().contains('corn')) base = 5.0;
    final predicted = base * area;
    setState(() {
      _result = 'Estimated yield: ${predicted.toStringAsFixed(2)} t';
    });
  }

  @override
  void dispose() {
    cropCtrl.dispose();
    areaCtrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(
      appBar: AppBar(title: const Text('Yield Prediction'), backgroundColor: primary),
      body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [
        GlassCard(child: Column(children: [const Text('Enter crop details', style: TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 8), TextField(controller: cropCtrl, decoration: const InputDecoration(labelText: 'Crop', border: OutlineInputBorder())), const SizedBox(height: 8), TextField(controller: areaCtrl, decoration: const InputDecoration(labelText: 'Area (ha)', border: OutlineInputBorder()), keyboardType: TextInputType.number), const SizedBox(height: 8), ElevatedButton(onPressed: _predict, style: ElevatedButton.styleFrom(backgroundColor: primary), child: const Text('Predict'))])),
        const SizedBox(height: 12),
        Expanded(child: Center(child: Text(_result ?? 'Prediction result will appear here', style: const TextStyle(color: Colors.black45))))
      ])),
    );
  }
}

class DetectorPage extends StatelessWidget {
  const DetectorPage({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return SafeArea(child: Padding(padding: const EdgeInsets.all(16.0), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Text('Detector', style: Theme.of(context).textTheme.titleLarge),
      const SizedBox(height: 12),
      GlassCard(child: Column(children: [const SizedBox(height: 8), Icon(Icons.camera_alt, size: 64, color: primary), const SizedBox(height: 12), const Text('Take a photo or upload an image for disease & nutrient suggestions', textAlign: TextAlign.center, style: TextStyle(color: Colors.black54)), const SizedBox(height: 12), Row(mainAxisAlignment: MainAxisAlignment.center, children: [ElevatedButton.icon(onPressed: () {}, icon: const Icon(Icons.camera), label: const Text('Camera')), const SizedBox(width: 12), OutlinedButton.icon(onPressed: () {}, icon: const Icon(Icons.upload_file), label: const Text('Upload'))]), const SizedBox(height: 12),])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Recent analyses will show here', style: TextStyle(color: Colors.black45)))),
    ])));
  }
}

class MicronutrientScreen extends StatelessWidget {
  const MicronutrientScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Micronutrient Analysis'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: [const Text('Upload soil lab or leaf image', style: TextStyle(fontWeight: FontWeight.w700)), const SizedBox(height: 12), Row(mainAxisAlignment: MainAxisAlignment.center, children: [ElevatedButton(onPressed: () {}, child: const Text('Upload')), const SizedBox(width: 8), OutlinedButton(onPressed: () {}, child: const Text('Camera'))])])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Micronutrient analysis results will appear here', style: TextStyle(color: Colors.black45)))),])));
  }
}

// Follow-up: more placeholder screens (SoilHealth, FertilizerPlanner, MicronutrientLab, MarketPrices, AgroCredits, CommunityLearning, AskExpert, ARPlaceholder, Explainability, CropRecommendation)
// For brevity they are similar to earlier placeholders — you can expand as needed.

class SoilHealthScreen extends StatelessWidget {
  const SoilHealthScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Soil Health'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Soil health details (NPK, pH, organic matter) placeholder')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Detailed soil metrics and recommendations will be here', style: TextStyle(color: Colors.black45))))])));
  }
}

class FertilizerPlannerScreen extends StatelessWidget {
  const FertilizerPlannerScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Fertiliser Planner'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Fertiliser planner placeholder — generate plan based on soil & crop')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Planner output will show here', style: TextStyle(color: Colors.black45))))])));
  }
}

class MicronutrientLabScreen extends StatelessWidget {
  const MicronutrientLabScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Micronutrient Lab Upload'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Upload lab PDF/image — parsing & extraction placeholder')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Upload results will appear here', style: TextStyle(color: Colors.black45))))])));
  }
}

class MarketPricesScreen extends StatelessWidget {
  const MarketPricesScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Market Prices'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Market prices placeholder — show commodity rates, locality selection')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Price charts & tables will be here', style: TextStyle(color: Colors.black45))))])));
  }
}

class AgroCreditsScreen extends StatelessWidget {
  const AgroCreditsScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Agro Credits'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Credits & transactions placeholder')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Your credit balance and history', style: TextStyle(color: Colors.black45))))])));
  }
}

class CommunityLearningScreen extends StatelessWidget {
  const CommunityLearningScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Community Learning'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Community feed placeholder — posts, Q&A, tips')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Community posts will be shown here', style: TextStyle(color: Colors.black45))))])));
  }
}

class AskExpertScreen extends StatelessWidget {
  const AskExpertScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Ask Expert'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Ask experts placeholder — submit question & attach image')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Expert answers & timeline', style: TextStyle(color: Colors.black45))))])));
  }
}

class ARPlaceholderScreen extends StatelessWidget {
  const ARPlaceholderScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('AR View'), backgroundColor: primary), body: Center(child: Padding(padding: const EdgeInsets.all(18.0), child: Column(mainAxisSize: MainAxisSize.min, children: const [Icon(Icons.view_in_ar, size: 80, color: Colors.grey), SizedBox(height: 12), Text('AR View will overlay disease markers on live camera', textAlign: TextAlign.center, style: TextStyle(color: Colors.black54))]))));
  }
}

class ExplainabilityScreen extends StatelessWidget {
  const ExplainabilityScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Explainability'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Model explainability placeholder — feature importance, reasons')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Explainability visuals will appear here', style: TextStyle(color: Colors.black45))))])));
  }
}

class CropRecommendationScreen extends StatelessWidget {
  const CropRecommendationScreen({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return Scaffold(appBar: AppBar(title: const Text('Crop Recommendation'), backgroundColor: primary), body: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [GlassCard(child: Column(children: const [Text('Crop recommendation placeholder — best crops for soil & weather')])), const SizedBox(height: 12), Expanded(child: Center(child: Text('Recommendations will appear here', style: TextStyle(color: Colors.black45))))])));
  }
}

//
// ---------------- INSIGHTS & PROFILE
//
class InsightsPage extends StatelessWidget {
  const InsightsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Insights', style: Theme.of(context).textTheme.titleLarge),
            const SizedBox(height: 12),

            // chart placeholder
            GlassCard(
              child: SizedBox(
                height: 160,
                child: Center(
                  child: Text(
                    'Yield trend chart placeholder',
                    style: TextStyle(color: Colors.black54),
                  ),
                ),
              ),
            ),

            const SizedBox(height: 12),
            Text('Recent Alerts', style: Theme.of(context).textTheme.titleMedium),
            const SizedBox(height: 8),

            Expanded(
              child: ListView(
                children: [
                  ListTile(
                    leading: Icon(Icons.warning, color: Colors.orange.shade700),
                    title: const Text('Pest alert near Village X'),
                    subtitle: const Text('2 hours ago'),
                  ),
                  ListTile(
                    leading: Icon(Icons.water_drop, color: Colors.blue.shade700),
                    title: const Text('Irrigation reminder for Field 2'),
                    subtitle: const Text('in 1 day'),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}


class ProfilePage extends StatelessWidget {
  const ProfilePage({super.key});
  @override
  Widget build(BuildContext context) {
    final primary = AgroVisionAIApp.primaryGreen;
    return SafeArea(child: Padding(padding: const EdgeInsets.all(16.0), child: Column(children: [Row(children: [CircleAvatar(radius: 36, backgroundColor: Colors.green.shade100, child: Icon(Icons.person, size: 36, color: primary)), const SizedBox(width: 12), const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Chirag Raje Urs', style: TextStyle(fontWeight: FontWeight.w700)), Text('Farmer • Karnataka', style: TextStyle(color: Colors.black54, fontSize: 12))])]), const SizedBox(height: 18), GlassCard(child: ListTile(leading: Icon(Icons.language, color: primary), title: const Text('Language'), subtitle: const Text('Kannada, Hindi, English'))), const SizedBox(height: 8), GlassCard(child: ListTile(leading: Icon(Icons.history, color: primary), title: const Text('Activity'), subtitle: const Text('Recent analyses & chats'))), const SizedBox(height: 8), GlassCard(child: ListTile(leading: Icon(Icons.account_balance_wallet, color: primary), title: const Text('Agro Credits'), subtitle: const Text('Balance: ₹1,200'))), const SizedBox(height: 18), ElevatedButton.icon(onPressed: () async { await FirebaseAuth.instance.signOut(); if (!kIsWeb) { try { await GoogleSignIn().signOut(); } catch (_) {} } Navigator.pushReplacement(context, MaterialPageRoute(builder: (_) => const LoginScreen())); }, style: ElevatedButton.styleFrom(backgroundColor: primary), icon: const Icon(Icons.logout), label: const Text('Sign out'))])));
  }
}
